### ISSUE TITLE
HTML5 Support

### ISSUE THREAD

**Issue by tech4him1** [Jonnyauk/Wonderflux#56]
Do you have HTML5 support yet?  If so, how can I enable it?

Thank You

**Comment by Jonnyauk** [comment]
Hi there,
yes - HTML5 support is in-place ;) Simply select the 'html5' option is 'document type' options section (this is in Appearance > WFX Advanced).

You may also want to override various template parts in your child theme to create <section> instead of div like <header> <footer> etc.

There is also 2 filters you can use for the main content wrapper to replace the <div class=""container" id="main-content"> and corresponding closing </div> - see index.php to see these 2 filters (which are 'wflux_layout_content_container_open' and 'wflux_layout_content_container_close')

**Comment by tech4him1** [comment]
Whenever I switch the "Document type" to html5, the website seems to produce duplicate `<html>` elements.  This happens whether I enable the Wonderflux parent theme or my child theme.
Here is the top of my source code:
```html
<!DOCTYPE html>
<html lang="en">

<html xml:lang="en" lang="en" xmlns="http://www.w3.org/1999/xhtml" >
<head>
...
```
I am using Wordpress 4.5.3 and Wonderflux 2.2. The duplicate elements show up even with all plugins disabled.

Thank You!

**Comment by Jonnyauk** [comment]
Ah - thanks for letting me know! I think you may have discovered a bug that's crept in there - I'll bug fix this as soon as I can and bundle it into a new release which is about due anyway. This will likely be a few days as I'm very busy with pia dwork right now and am heading to the WordCamp Brighton WordPress conference in a few days - so I have a-lot to do before I finish up this week ;(

**Comment by Jonnyauk** [comment]
This has now been fixed - thanks for reporting bug (really!!)

I know what caused this now - some time ago I switched WordPress to use the core WordPress filter 'language_attributes' within the function that builds this output but forgot to test when html5 document type was selected.

This will be incorporated into the next release (v2.3) which I should have wrapped-up soon!

**Comment by Jonnyauk** [comment]
I've also now added in html5 support with WordPress add_theme_support, see commit mentioned above aa779d8308dabfcd408c8c78603b08c7635bd020

**Comment by tech4him1** [comment]
Maybe I am just completely missing something, but how do I set the doctype from my child theme (without going to the admin options)?

**Comment by Jonnyauk** [comment]
You will find the option for doc type in the Wonderflux admin menu (Wonderflux -> Advanced)

**Comment by tech4him1** [comment]
OK, is there any way to do it from a hook or function instead of going to the admin options?

**Comment by tech4him1** [comment]
What version of IE is Wonderflux offically supported on?

The reason I was asking is that for full HTML5 support it might be good to include the [html5shiv script](https://github.com/aFarkas/html5shiv/) with an IE8 conditional comment. If you are not planning on supporting IE8 since [MS is not even supporting anymore on desktop Windows](https://support.microsoft.com/en-us/lifecycle?forceorigin=esmc#gp/Microsoft-Internet-Explorer) that is fine with me, I can just add it to my child theme.
