### ISSUE TITLE
How to make one page template files

### ISSUE THREAD

**Issue by stefvanriet** [Jonnyauk/Wonderflux#60]
Hi,

I need to make a template file for a single page (called agenda). On regular Wordpress this would be 'page-{slug}.php', so page-agenda.php. This doesn't work on Wonderflux, neither does loop-content-agenda.php. I read the documentation and the other issues on github but I don't understand them. Can you tell me what to do and be really specific about it? Thanks.

Kind regards,

Stef

**Comment by Jonnyauk** [comment]
Wonderflux doesn't currently support detecting page slugs in the extended `get_template_part` internal function, but does fully support the WordPress template hierarchy:

## dedicated file (just for a specific page)
- You are almost there! Just duplicate 'page.php' from the Wonderflux directory and put it in your child theme. Then re-name file as per normal WordPress conventions - so in your example you'd re-name it page-agenda.php
- I think the mistake you were making here is that you were not duplicating the core Wonderflux page.php

## Use is_page() in loop-content
- Depending on what you want to do with the page, you may just need to create loop-content-page.php or loop-content.php (or any of the other template part files for that matter! Then just use `is_page('agenda')` to conditionally check for specific page - which is a much simpler way of doing things - see https://developer.wordpress.org/reference/functions/is_page/#user-contributed-notes or https://codex.wordpress.org/Conditional_Tags for more info on this.

## page template (re-usable page template)
- duplicate 'page.php' from the Wonderflux directory and put it in your child theme.
- add custom page definition at top of file: https://developer.wordpress.org/themes/template-files-section/page-template-files/page-templates/#creating-custom-page-templates-for-global-use
- Select your new page template in admin when editing your page

**Comment by stefvanriet** [comment]
I copied 'loop-content-page' instead of 'page', that was my mistake. It works now. Thank you for your support.

Kind regards,

Stef
