### ISSUE TITLE
Add a front-page.php.

### ISSUE THREAD

**Issue by tech4him1** [Jonnyauk/Wonderflux#61]
Is Wonderflux location aware for "front-page" instead of just "-home"?  I am wanting to make a template that shows on the home page whether it is a post page or a static page.

**Comment by Jonnyauk** [comment]
Yes, Wonderflux adheres to WordPress theme standards in almost all aspects.

**Comment by tech4him1** [comment]
OK, `loop-content-front-page.php` did not seem to be working, maybe I need to try again.  I was just wondering if it was because there is no `front-page.php` in Wonderflux.

**Comment by Jonnyauk** [comment]
Ah - you'll need to name the file `loop-content-home.php`, rather than `loop-content-front-page.php` ;)

**Comment by Jonnyauk** [comment]
Also, you can duplicate `page.php` from the Wonderflux directory into your child theme and re-name it `home.php` or `front-page.php` **if you really need to advanced stuff** - but in almost ALL instances you'd be best to use `loop-content-home.php`

**Comment by tech4him1** [comment]
OK.  I can probably do that.  The reason I was wanting a `loop-content-front-page.php` is because in my understanding, `home.php` is used on the posts page and not on a static home page, while `front-page.php` is always used on the home page, whether it is static or not.
