### ISSUE TITLE
Overflow Flux Layout or insert nav within layout

### ISSUE THREAD

**Issue by stefvanriet** [Jonnyauk/Wonderflux#62]
Hi,

I'm trying to place a nav around the middle of a page for a front page. (see http://darylkeep.com/ )

What's the best way to let the nav overflow so it fills the full width? Placing the nav outside of Flux Layout means it doesn't respect collapsing on smaller screens, inside of Flux Layout it gets centered and doesn't reach the full width.

What would you recommend?

**Comment by Jonnyauk** [comment]
I'm afraid that needs separate CSS - Flux Layout simply creates responsive containers for you to put content in, it doesn't style content as such.

If you want it wider, simply change the container percentage width (in the WordPress admin area go to Appearance -> WFX Stylelab or go to the top of the screen and click on 'Sylelab' under the Wonderflux dropdown) in the standard WordPress admin bar. The option you want to change is 'Site container width %'

Alternatively, you could create a new 'container' class, something like this:

<div class="container container-wide">
Your content here
</div>

... and then setup a new CSS rule in your child theme style.css to make this wider than the standard content width.

**Comment by stefvanriet** [comment]
Site container width % is really helpful, I didn't realise I set this. I always feel like it's easier to narrow content rather than widen it.

**Comment by Jonnyauk** [comment]
No problemo - different creative designs work for different sites ;)
