### ISSUE TITLE
Update Integration

### ISSUE THREAD

**Issue by tech4him1** [Jonnyauk/Wonderflux#63]
Have you ever thought of adding automatic update integration with Wordpress, similar to what https://github.com/afragen/github-updater does?

**Comment by Jonnyauk** [comment]
Sure thing - and good suggestion, updates through the WordPress admin would be nice; I'm a bit lazy on this as I use DeployHQ to auto-deploy to a-lot of my servers that run Wonderflux ;) 

However, I'm hoping to one day get Wonderflux into the official WordPress.org theme repo, which would allow really nice upgrade integration. 

If I'm honest I'm not 100% what their stance is with frameworks (although it does pass all theme validation checks). I'm at WordCamp Manchester at the end of October and I'll try and have a chat with a few guys who could maybe advise me if it's worth putting in the final push to get this onto WordPress.org.

**Comment by tech4him1** [comment]
OK, great!  Let me know when/if you do!

**Comment by tech4him1** [comment]
Did you get a chance to decide what you are doing for updating?
