### ISSUE TITLE
Header goes wrong on big screens

### ISSUE THREAD

**Issue by stefvanriet** [Jonnyauk/Wonderflux#64]
Hi,

I'm having a problem with the Flux Layout. On really big screens (>1392-ish px) the width of the menu-items of my top menu collapses. Any idea what could cause this? This is the website: www.darylkeep.com/aanbod It only happens in the top bar, which seems weird to me. Thanks in advance!

**Comment by stefvanriet** [comment]
welp, I think I just need to change mq-medium to mq-medium-min . Will delete this in a minute if that is correct

**Comment by stefvanriet** [comment]
Yep, that did it. I was supposed to get this site online tonight so I was too stressed to figure out the obvious solution. Please delete or close this because it looks like I can't.

**Comment by Jonnyauk** [comment]
No probs - yes the '-min' CSS is particularly useful as it cascades down the media queries ;)
