### ISSUE TITLE
How to add comments to pages

### ISSUE THREAD

**Issue by stefvanriet** [Jonnyauk/Wonderflux#65]
Hi,

I started out with the demo theme. I'm having trouble showing comments to pages. I can see the comments on Twenty Fifteen theme. I made a blog page which should show links and amount of comments (the standard functionality), but I'm not sure how to add this. Comments are visible in single posts though. Thanks in advance.

**Comment by Jonnyauk** [comment]
Standard WordPress functionality, not an issue with Wonderflux buddy ;)
