### ISSUE TITLE
newsmag

### ISSUE THREAD

**Issue by sundanes** [Jonnyauk/Wonderflux#67]
Ingin theme gratis newsmag rasa premium

**Comment by Jonnyauk** [comment]
Hi, I'm afraid that Wonderflux is a theme framework built for developers to create their own child themes for - it doesn't provide any 'design' as such (deliberately actually - so ANY site can be coded with it!). 

Sure - it would be no problem to create a 'premium news theme' with Wonderflux - however, it's 100% up to you to develop such a theme!
